doctrine:
    dbal:
        connections:
            default:
                url: '%env(DATABASE_URL)%'
            eventstore:
                url: '%env(EVENTSTORE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src'
                prefix: 'App'
                alias: App
